name: 'Azure Deployment'

on:
  push:
    branches:
      - master
    paths-ignore:
      - '**.md'

jobs:
  build:
    name: Build App
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18.17.1'
          cache: 'npm'
      - name: Install npm packages and build
        run: |
          npm install --include=dev
          npm run build
          rm -rf node_modules
      - name: Zip artifact
        run: zip kambot-v2.zip ./* -r
      - name: Upload artifact for deployment job
        uses: actions/upload-artifact@v4
        with:
          name: kambot-v2
          path: kambot-v2.zip
  deploy-a:
    name: Deploy to Azure (A)
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Download artifact from build job
        uses: actions/download-artifact@v4
        with:
          name: kambot-v2
      - name: Deploy (kambot-v2)
        uses: azure/webapps-deploy@v3
        with:
          app-name: kambot-v2
          slot-name: 'production'
          publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE_A }}
          package: kambot-v2.zip
  deploy-b:
    name: Deploy to Azure (B)
    runs-on: ubuntu-latest
    if: false # Disable it
    needs: build
    steps:
      - name: Download artifact from build job
        uses: actions/download-artifact@v4
        with:
          name: kambot-v2
      - name: Deploy (kambot-v2-b)
        uses: azure/webapps-deploy@v3
        with:
          app-name: kambot-v2-b
          slot-name: 'production'
          publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE_B }}
          package: kambot-v2.zip
